conf/urls.py
from django.urls import path, include
from django.views.generic.base import RedirectView
from django.views.i18n import JavaScriptCatalog
from django.conf.urls import url
# from django.contrib import admin
# from rest_framework import routers
# from common import views as common_views
from rest_framework_jwt.views import obtain_jwt_token


# router = routers.DefaultRouter()
# router.register(r'users', common_views.UserViewSet)

urlpatterns = [
    # use rest_framework router instead of URL conf
    # path('', include(router.urls)),

    # api authorization
    url(r'^api-token-auth/', obtain_jwt_token),
    # url('api-auth/', include('rest_framework.urls', namespace='rest_framework')),

    # shared
    path('favicon.ico', RedirectView.as_view(url=r'static/favicon.ico')),
    path('jsi18n/', JavaScriptCatalog.as_view(), name='javascript-catalog'),

    # app
    path('', include('common.urls')),
    # path('admin/', admin.site.urls),
]

demo/urls.py
from django.urls import path
from . import views


app_name = 'demo'

urlpatterns = [
    path('', views.RecordListView.as_view(), name='records-default'),
    path('records/', views.RecordListView.as_view(), name='records'),
    path('record/<int:pk>', views.RecordDetailView.as_view(), name='record-detail'),
    path('records-json/', views.RecordListJsonView.as_view(), name='records-json'),
    # path('records-json/', views.test_json, name='records-json'),
]

demo/models.py
import datetime
from django.db import models
from django.utils.translation import gettext_lazy as _


class Record(models.Model):
    name = models.CharField(_('Record.Name'), max_length=50, null=False, blank=False)
    age = models.IntegerField(_('Record.Age'), null=True, blank=True)
    gender = models.CharField(_('Record.Gender'), max_length=1, null=True, blank=True, choices=(
        ('M', _('DICT.GENDER.Male')),
        ('F', _('DICT.GENDER.Female')),
    ))
    date_of_birth = models.DateField(_('Record.DateOfBirth'), null=False, blank=False, default=datetime.datetime(1981, 1, 1))
    create_time = models.DateTimeField(_('Record.CreateTime'), auto_now_add=True)
    update_time = models.DateTimeField(_('Record.UpdateTime'), auto_now=True)

    class Meta:
        verbose_name = _('Record.ModelVerboseName')
        verbose_name_plural = _('Record.ModelVerboseNamePlural')

    def __str__(self):
        return self.name

demo/forms.py
from django.forms import ModelForm
from .models import Record


class RecordModelForm(ModelForm):
    class Meta:
        model = Record
        fields = "__all__"

demo/views.py
from django.views.generic import ListView, DetailView
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from .models import Record
from common.list import JsonListView
from django.http.response import JsonResponse
import datetime


# Create your views here.
class RecordListView(LoginRequiredMixin, ListView):
    model = Record
    paginate_by = 1
    # template_name = 'demo/record_list.html'
    # context_object_name = 'object'

    # def get_queryset(self):
    #     return Record.objects.all()


class RecordListJsonView(JsonListView):
    model = Record
    paginate_by = 5


class RecordDetailView(LoginRequiredMixin, DetailView):
    model = Record
    # template_name = 'demo/record_detail.html'


def test_json(request):
    kw = {'code': 0,
          'msg': 'success',
          'data': [
              {
                  'id': 1,
                  'name': 'a1'
              },
              {
                  'id': 2,
                  'name': 'b2'
              },
              {
                  'id': 3,
                  'name': 'c3'
              }
          ],
          'page': {
              'page_size': 5,
              'page': 1
          }}

    kw2 = {
        'id': 1,
        'name': 'aaa',
        'gender': 'M',
        'date_of_birth': datetime.date(1981, 1, 1),
        'create_time': datetime.datetime.now(),
        'update_time': datetime.datetime.now()
    }
    record = Record(kw2)

    return JsonResponse(record, safe=False)

demo/templates/demo/record_detail.html
{% extends "base_generic.html" %}

{% block title %}<title>Record</title>{% endblock %}

{% block content %}
<!-- Breadcrumbs-->
<ol class="breadcrumb">
    <li class="breadcrumb-item">
        <a href="#">Record</a>
    </li>
    <li class="breadcrumb-item active">All List</li>
</ol>

<!-- DataTables Example -->
<div class="card mb-3">
    <div class="card-header">
        <i class="fas fa-table"></i>
        Record
    </div>
    <div class="card-body">

    </div>
    <div class="card-footer small text-muted">Updated yesterday at 11:59 PM</div>
</div>
{% endblock %}

demo/templates/demo/record_json_list.html
{% extends "base_generic.html" %}

{% block title %}<title>Record</title>{% endblock %}

{% block content %}
<!-- Breadcrumbs-->
<ol class="breadcrumb">
    <li class="breadcrumb-item">
        <a href="#">Record</a>
    </li>
    <li class="breadcrumb-item active">All List</li>
</ol>

<!-- DataTables Example -->
<div class="card mb-3">
    <div class="card-header">
        <i class="fas fa-table"></i>
        Record
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>id</th>
                        <th>name</th>
                        <th>age</th>
                        <th>gender</th>
                        <th>date_of_birth</th>
                        <th>create_time</th>
                        <th>update_time</th>
                    </tr>
                </thead>
                <tbody>
                {{ object_list }}
                </tbody>
            </table>
        </div>
    </div>
    <div class="card-footer small text-muted">Updated yesterday at 11:59 PM</div>
</div>
{% endblock %}

demo/templates/demo/record_list.html
{% extends "common/base.html" %}
{% load bootstrap_pagination %}
{% load i18n %}

{% block title %}<title>Record List</title>{% endblock %}
{% block content %}
    <!-- Breadcrumbs-->
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a href="#">Demo</a>
        </li>
        <li class="breadcrumb-item active">Record List (Class)</li>
    </ol>

    <div class="card mb-3">
        <div class="card-header">
            <span class="fas fa-table"></span>
            Record List
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <div class="row">
                    <div class="col-sm-12">
                        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                            <thead>
                            <tr>
                                <th>#</th>
                                <th>{% trans 'Record.Name' %}</th>
                                <th>{% trans 'Record.Age' %}</th>
                                <th>{% trans 'Record.Gender' %}</th>
                                <th>{% trans 'Record.DateOfBirth' %}</th>
                                <th>{% trans 'Record.CreateTime' %}</th>
                                <th>{% trans 'Record.UpdateTime' %}</th>
                            </tr>
                            </thead>
                            <tbody>
                                {% for obj in object_list %}
                                <tr>
                                    <td><a href="{% url 'demo:record-detail' obj.pk %}">{{ obj.pk }}</a></td>
                                    <td>{{ obj.name }}</td>
                                    <td>{{ obj.age }}</td>
                                    <td>{{ obj.gender }}</td>
                                    <td>{{ obj.date_of_birth }}</td>
                                    <td>{{ obj.create_time }}</td>
                                    <td>{{ obj.update_time }}</td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-12">
                        {% bootstrap_paginate page_obj show_first_last="true" extra_pagination_classes="justify-content-center" %}
                    </div>
                </div>
            </div>
        </div>
        <div class="card-footer small text-muted" id="update_time"></div>
    </div>
{% endblock %}

{% block javascript %}
    <script type="text/javascript">
    $(document).ready(function() {
        dt = new Date()
        $("#update_time").text("Updated " + dt.toLocaleDateString() + " at " + dt.toLocaleTimeString())
    })
    </script>
{% endblock %}