common/urls.py
from django.urls import path
from . import views


app_name = 'common'

api_user_list = views.UserApiViewSet.as_view({
    'get': 'list',
    'post': 'create'
})

api_user_detail = views.UserApiViewSet.as_view({
    'get': 'retrieve',
    'put': 'update',
    'delete': 'destroy'
})


urlpatterns = [
    path('api/users/', api_user_list, name='api-user-list'),
    path('api/users/<int:pk>/', api_user_detail, name='api-user-detail'),
    # path('login/', views.UserLoginView.as_view(), name='login'),

    path('users/', views.UserListView.as_view(), name='users'),
    path('user/<int:pk>', views.UserDetailView.as_view(), name='user-detail'),

    path('user/create/', views.UserCreateView.as_view(), name='user-create'),
    # path('user/<int:pk>/update/', views.UserUpdateView.as_view(), name='user-update'),
    # path('user/<int:pk>/delete/', views.UserDeleteView.as_view(), name='user-delete'),
]

conf/urls.py
from django.urls import path, include
from django.views.generic.base import RedirectView
from django.views.i18n import JavaScriptCatalog
from django.conf.urls import url
# from django.contrib import admin
# from rest_framework import routers
# from common import views as common_views
from rest_framework_jwt.views import obtain_jwt_token


# router = routers.DefaultRouter()
# router.register(r'users', common_views.UserViewSet)

urlpatterns = [
    # use rest_framework router instead of URL conf
    # path('', include(router.urls)),

    # api authorization
    url(r'^api-token-auth/', obtain_jwt_token),
    # url('api-auth/', include('rest_framework.urls', namespace='rest_framework')),

    # shared
    path('favicon.ico', RedirectView.as_view(url=r'static/favicon.ico')),
    path('jsi18n/', JavaScriptCatalog.as_view(), name='javascript-catalog'),

    # app
    path('', include('common.urls')),
    # path('admin/', admin.site.urls),
]

common/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, UserManager
from django.utils.translation import gettext_lazy as _
from django.utils.translation import gettext


class User(AbstractBaseUser):
    # file_prepend = "users/profile_pics"
    username = models.CharField(_('user.username'), max_length=100, unique=True)
    password = models.CharField(_('user.password'), max_length=128)
    first_name = models.CharField(_('user.first_name'), max_length=150, blank=True)
    last_name = models.CharField(_('user.last_name'), max_length=150, blank=True)
    email = models.EmailField(_('user.email'), max_length=255, unique=True)
    last_login = models.DateTimeField(_('user.last_login'), blank=True, null=True)
    is_active = models.BooleanField(_('user.is_active'), default=True)
    is_superuser = models.BooleanField(_('user.is_superuser'), default=False)
    is_staff = models.BooleanField(_('user.is_staff'), default=False)
    date_joined = models.DateTimeField(_('user.date_joined'), auto_now_add=True)
    # role = models.CharField(_('user.role'), max_length=50, choices=ROLES)
    # profile_pic = models.FileField(_('user.profile_pic'), max_length=1000, upload_to=img_url, null=True, blank=True)

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['password', 'email']

    objects = UserManager()

    class Meta:
        verbose_name = _("User")
        verbose_name_plural = _("Users")

common/views.py
from rest_framework import viewsets
from rest_framework import permissions
from rest_framework.authentication import SessionAuthentication
from rest_framework_jwt.authentication import JSONWebTokenAuthentication
from django.views.generic import TemplateView
from .models import User
from .serializers import UserSerializer

# from django.utils.translation import gettext as _


class UserApiViewSet(viewsets.ModelViewSet):
    permission_classes = [permissions.IsAuthenticatedOrReadOnly]
    queryset = User.objects.all().order_by('-date_joined')
    serializer_class = UserSerializer
    authentication_classes = (JSONWebTokenAuthentication, SessionAuthentication)

    def get_serializer_class(self):
        pass
        # https://blog.51cto.com/haoyonghui/2425999


class UserListView(TemplateView):
    template_name = 'common/user_list.html'


class UserDetailView(TemplateView):
    template_name = 'common/user_detail.html'


class UserCreateView(TemplateView):
    template_name = 'common/user_form.html'

common/templates/common/user_detail.html
{% extends "common/base.html" %}
{% load i18n %}

{% block css %}{% endblock %}

{% block content %}
    <!-- Breadcrumbs-->
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a href="#">系統管理</a>
        </li>
        <li class="breadcrumb-item active">用戶管理</li>
    </ol>

    <div class="card mb-3">
        <div class="card-header">
            <span class="fas fa-table"></span>
            用戶信息
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-striped table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                    <tr>
                        <th>#</th>
                        <th>{% trans 'user.username' %}</th>
                        <th>{% trans 'user.last_name' %}</th>
                        <th>{% trans 'user.first_name' %}</th>
                        <th>{% trans 'user.email' %}</th>
                        <th>{% trans 'user.is_active' %}</th>
                        <th>{% trans 'user.is_superuser' %}</th>
                        <th>{% trans 'user.last_login' %}</th>
                        <th>{% trans 'user.date_joined' %}</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for obj in results %}
                        <tr>
                            <td><a href="#">{{ obj.id }}</a></td>
                            <td>{{ obj.username }}</td>
                            <td>{{ obj.last_name }}</td>
                            <td>{{ obj.first_name }}</td>
                            <td>{{ obj.email }}</td>
                            <td>{{ obj.is_active }}</td>
                            <td>{{ obj.is_superuser }}</td>
                            <td>{{ obj.last_login }}</td>
                            <td>{{ obj.date_joined }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        <div class="card-footer small text-muted" id="refresh_time"></div>
    </div>
{% endblock %}

{% block javascript %}
    <script type="text/javascript">
        $(document).ready(function () {
            $('#dataTable').DataTable({
                "stateSave": true,
                "pagingType": "full_numbers",
                "scrollX": true,
                "lengthMenu": [[10, 1, 2, -1], [10, 1, 2, "All"]],
                "processing": true,
                "select": true,
                //"serverSide": true,
                //"ajax": "../server_side/scripts/server_processing.php",
            });

            dt = new Date()
            $("#refresh_time").text("Page refreshed " + dt.toLocaleDateString() + " @" + dt.toLocaleTimeString())
        })
    </script>
{% endblock %}

common/templates/common/user_form.html
{% extends "common/base.html" %}
{% load i18n %}

{% block css %}{% endblock %}

{% block content %}
    <!-- Breadcrumbs-->
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a href="#">系統管理</a>
        </li>
        <li class="breadcrumb-item active">用戶管理</li>
    </ol>

    <div class="card mb-3">
        <div class="card-header">
            <span class="fas fa-table"></span>用户新建
        </div>
        <div class="card-body">
            <form>
                {% csrf_token %}
                <div class="form-group">
                    <div class="form-row">
                        <div class="col-md-6">
                            <div class="form-label-group">
                                <input type="text" id="firstName" class="form-control" placeholder="First name"
                                       required="required" autofocus="autofocus">
                                <label for="firstName">First name</label>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-label-group">
                                <input type="text" id="lastName" class="form-control" placeholder="Last name"
                                       required="required">
                                <label for="lastName">Last name</label>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <div class="form-label-group">
                        <input type="email" id="inputEmail" class="form-control" placeholder="Email address"
                               required="required">
                        <label for="inputEmail">Email address</label>
                    </div>
                </div>
                <div class="form-group">
                    <div class="form-row">
                        <div class="col-md-6">
                            <div class="form-label-group">
                                <input type="password" id="inputPassword" class="form-control" placeholder="Password"
                                       required="required">
                                <label for="inputPassword">Password</label>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-label-group">
                                <input type="password" id="confirmPassword" class="form-control"
                                       placeholder="Confirm password" required="required">
                                <label for="confirmPassword">Confirm password</label>
                            </div>
                        </div>
                    </div>
                </div>
                <input type="button" class="btn btn-primary" id="back" value="Back"/>
                <input type="submit" class="btn btn-primary" id="save" value="Save"/>
            </form>
        </div>
    </div>
{% endblock %}

{% block javascript %}
    <script type="text/javascript">
        $("#back").click(function () {
            window.location.href = "{% url 'common:users' %}"
        });

        $("#save").click(function () {
            $.ajax({
                url: "{% url 'common:api-user-list' %}",
                async: false,
                type: 'POST',
                data: {

                },
                success: function () {
                    alert('success');
                    window.location.href = "{% url 'common:users' %}";
                },
                error: function (jqXHR, textStatus, errorThrown) {
                    alert(jqXHR.status + ' ' + textStatus + ' ' + errorThrown)
                }
            })
        });
    </script>
{% endblock %}

common/templates/common/user_list.html
{% extends "common/base.html" %}
{% load i18n %}

{% block css %}{% endblock %}

{% block content %}
    <!-- Breadcrumbs-->
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a href="#">系統管理</a>
        </li>
        <li class="breadcrumb-item active">用戶管理</li>
    </ol>

    <div class="card mb-3">
        <div class="card-header">
            <span class="fas fa-table"></span>
            用戶列表
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-striped table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                    <tr>
                        <th>#</th>
                        <th>{% trans 'user.username' %}</th>
                        <th>{% trans 'user.last_name' %}</th>
                        <th>{% trans 'user.first_name' %}</th>
                        <th>{% trans 'user.email' %}</th>
                        <th>{% trans 'user.is_active' %}</th>
                        <th>{% trans 'user.is_superuser' %}</th>
                        <th>{% trans 'user.last_login' %}</th>
                        <th>{% trans 'user.date_joined' %}</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for obj in results %}
                        <tr>
                            <td><a href="#">{{ obj.id }}</a></td>
                            <td>{{ obj.username }}</td>
                            <td>{{ obj.last_name }}</td>
                            <td>{{ obj.first_name }}</td>
                            <td>{{ obj.email }}</td>
                            <td>{{ obj.is_active }}</td>
                            <td>{{ obj.is_superuser }}</td>
                            <td>{{ obj.last_login }}</td>
                            <td>{{ obj.date_joined }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        <div class="card-footer small text-muted" id="refresh_time"></div>
    </div>
{% endblock %}

{% block javascript %}
    <script type="text/javascript">
        $('#dataTable').DataTable({
            "stateSave": true,
            "pagingType": "full_numbers",
            "scrollX": true,
            "lengthMenu": [[10, 1, 2, -1], [10, 1, 2, "All"]],
            "processing": true,
            "select": true,
            "buttons": [
                {
                    "text": 'New',
                    "url": "{% url 'common:user-create' %}",
                    "action": function (e, dt, node, config) {
                        window.location.href = config.url
                    }
                }
            ]
        });

        dt = new Date()
        $("#refresh_time").text("Page refreshed " + dt.toLocaleDateString() + " @" + dt.toLocaleTimeString())
    </script>
{% endblock %}

{#            "serverSide": true,#}
{#            "ajax": {#}
{#                "url": "{% url 'common:api-user-list' %}",#}
{#                "type": "GET"#}
{#            },#}