accounts/urls.py
from django.urls import path, include
from . import views


app_name = 'accounts'

urlpatterns = [
    # path('', include('django.contrib.auth.urls')),
    path('login/', views.AccountsLoginView.as_view(), name='login'),
    path('logout/', views.AccountsLogoutView.as_view(), name='logout'),

    path('password_change/', views.AccountsPasswordChangeView.as_view(), name='password_change'),
    path('password_change/done/', views.AccountsPasswordChangeDoneView.as_view(), name='password_change_done'),

    path('password_reset/', views.AccountsPasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', views.AccountsPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', views.AccountsPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', views.AccountsPasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

conf/urls.py
from django.urls import path, include
from django.views.generic.base import RedirectView
from django.views.i18n import JavaScriptCatalog
from django.conf.urls import url
# from django.contrib import admin
# from rest_framework import routers
# from common import views as common_views
from rest_framework_jwt.views import obtain_jwt_token


# router = routers.DefaultRouter()
# router.register(r'users', common_views.UserViewSet)

urlpatterns = [
    # use rest_framework router instead of URL conf
    # path('', include(router.urls)),

    # api authorization
    url(r'^api-token-auth/', obtain_jwt_token),
    # url('api-auth/', include('rest_framework.urls', namespace='rest_framework')),

    # shared
    path('favicon.ico', RedirectView.as_view(url=r'static/favicon.ico')),
    path('jsi18n/', JavaScriptCatalog.as_view(), name='javascript-catalog'),

    # app
    path('', include('common.urls')),
    # path('admin/', admin.site.urls),
]

demo/urls.py
from django.urls import path
from . import views


app_name = 'demo'

urlpatterns = [
    path('', views.RecordListView.as_view(), name='records-default'),
    path('records/', views.RecordListView.as_view(), name='records'),
    path('record/<int:pk>', views.RecordDetailView.as_view(), name='record-detail'),
    path('records-json/', views.RecordListJsonView.as_view(), name='records-json'),
    # path('records-json/', views.test_json, name='records-json'),
]

soccer/urls.py
from django.urls import path
from . import views


app_name = 'soccer'

urlpatterns = [
    path('', views.index, name='index'),
    path('match', views.matches, name='match'),
    path('api/match/fetch_all', views.api_match_fetch_all, name='api_match_fetch_all'),
    path('charts', views.charts, name='charts'),
]

soccer/models.py
from django.db import models


# Create your models here.
class Nation(models.Model):
    name = models.CharField(name='name', verbose_name=r'国家', max_length=100)
    create_time = models.DateTimeField(name='create_time', verbose_name=r'创建时间', auto_now_add=True)
    update_time = models.DateTimeField(name='update_time', verbose_name=r'更新时间', auto_now=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = r'国家'
        verbose_name_plural = verbose_name


class Team(models.Model):
    name = models.CharField(name='name', verbose_name=r'队伍', max_length=100)
    abbr_name = models.CharField(name='abbr_name', verbose_name=r'缩写', max_length=20)
    nation = models.ForeignKey(Nation, on_delete=models.CASCADE, verbose_name=r'国家')
    create_time = models.DateTimeField(name='create_time', verbose_name=r'创建时间', auto_now_add=True)
    update_time = models.DateTimeField(name='update_time', verbose_name=r'更新时间', auto_now=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = r'队伍'
        verbose_name_plural = verbose_name


class League(models.Model):
    name = models.CharField(name='name', verbose_name=r'联赛', max_length=100)
    season = models.CharField(name='season', verbose_name=r'赛季', max_length=20)
    nation = models.ForeignKey(Nation, on_delete=models.CASCADE, verbose_name=r'国家')
    create_time = models.DateTimeField(name='create_time', verbose_name=r'创建时间', auto_now_add=True)
    update_time = models.DateTimeField(name='update_time', verbose_name=r'更新时间', auto_now=True)

    def __str__(self):
        return '%s %s' % (self.name, self.season)

    class Meta:
        verbose_name = r'联赛'
        verbose_name_plural = verbose_name


class Schedule(models.Model):
    name = models.CharField(name='name', verbose_name=r'赛程', max_length=20)
    league = models.ForeignKey(League, on_delete=models.CASCADE, verbose_name=r'联赛')
    start_date = models.DateField(name='start_date', verbose_name=r'开始日期')
    end_date = models.DateField(name='end_date', verbose_name=r'结束日期')
    create_time = models.DateTimeField(name='create_time', verbose_name=r'创建时间', auto_now_add=True)
    update_time = models.DateTimeField(name='update_time', verbose_name=r'更新时间', auto_now=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = r'赛程'
        verbose_name_plural = verbose_name


class Match(models.Model):
    # name = models.CharField(name='name', verbose_name=r'比赛', max_length=100)
    schedule = models.ForeignKey(Schedule, on_delete=models.CASCADE, verbose_name=r'轮次')
    home_team = models.ForeignKey(Team, on_delete=models.CASCADE, related_name='home_team_set', verbose_name=r'主队')
    away_team = models.ForeignKey(Team, on_delete=models.CASCADE, related_name='away_team_set', verbose_name=r'客队')
    home_score = models.IntegerField(name='home_score', verbose_name=r'主队得分', null=True, blank=True)
    away_score = models.IntegerField(name='away_score', verbose_name=r'客队得分', null=True, blank=True)
    schedule_date = models.DateField(name='schedule_date', verbose_name=r'预计比赛日期')
    match_date = models.DateField(name='match_date', verbose_name=r'实际比赛日期', null=True, blank=True)
    create_time = models.DateTimeField(name='create_time', verbose_name=r'创建时间', auto_now_add=True)
    update_time = models.DateTimeField(name='update_time', verbose_name=r'更新时间', auto_now=True)

    def __str__(self):
        return '%s vs %s @%s' % (self.home_team, self.away_team, self.schedule_date)

    class Meta:
        verbose_name = r'比赛'
        verbose_name_plural = verbose_name


class Test(models.Model):
    name = models.CharField(name='name', verbose_name=r'姓名', max_length=100)
    age = models.IntegerField(name='age', verbose_name=r'年龄')
    create_time = models.DateTimeField(name='create_time', verbose_name=r'创建时间', auto_now_add=True)
    update_time = models.DateTimeField(name='update_time', verbose_name=r'更新时间', auto_now=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = r'测试'
        verbose_name_plural = verbose_name

soccer/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth.decorators import login_required
from django.views import generic
from .models import Match
import json


# Create your views here.
def matches(request):
    return render(request, template_name='soccer/match.html')


# @csrf_exempt
def api_match_fetch_all(request):
    if request.method == 'GET':
        return HttpResponse(json.dumps("do not support GET method"), content_type="application/json")

    print('==========================api_match_fetch_all===========================')
    for item in request.POST.items():
        print(item)

    all_matches = Match.objects.order_by('schedule_date')

    draw = int(request.POST['draw'])
    print("draw =", draw)
    start = int(request.POST['start'])
    print("start =", start)
    length = int(request.POST['length'])
    print("length =", length)
    paginator = Paginator(object_list=all_matches, per_page=length)

    matches = None
    try:
        # print("page index (est.) =", start // length)
        matches = paginator.page(start // length)
    except PageNotAnInteger:
        matches = paginator.page(1)
    except EmptyPage:
        matches = paginator.page(paginator.num_pages)

    data = list()
    for m in matches.object_list:
        match = {
            "schedule": "%s" % m.schedule,
            "home_team": "%s" % m.home_team,
            "home_score": m.home_score,
            "away_score": m.away_score,
            "away_team": "%s" % m.away_team,
            "schedule_date": "%s" % m.schedule_date,
            "match_date": "%s" % m.match_date,
            "create_time": "%s" % m.create_time,
            "update_time": "%s" % m.update_time
        }
        data.append(match)

    resp = {
        'draw': draw,
        'recordsTotal': paginator.count,
        'recordsFiltered': paginator.count,
        'data': data
    }
    print('==========================api_match_fetch_all===========================')
    return HttpResponse(json.dumps(resp), content_type="application/json")


@login_required
def index(request):
    return render(request, 'index.html', locals())


def charts(request):
    return render(request, 'soccer/charts.html', locals())

soccer/templates/base_generic.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  {% block title %}<title>Dashboard</title>{% endblock %}

  <!-- Custom fonts for this template-->
  <link href="{% static 'fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">

  <!-- Page level plugin CSS-->
  <link href="{% static 'datatables/dataTables.bootstrap4.css' %}" rel="stylesheet">

  <!-- Custom styles for this template-->
  <link href="{% static 'css/sb-admin.css' %}" rel="stylesheet">

</head>

<body id="page-top">
  <!-- Navbar -->
  <nav class="navbar navbar-expand navbar-dark bg-dark static-top">
    <a class="navbar-brand mr-1" href="{% url 'soccer:index' %}">Django Project - Soccer</a>

    <button class="btn btn-link btn-sm text-white order-1 order-sm-0" id="sidebarToggle" href="#">
        <i class="fas fa-bars"></i>
    </button>

    <!-- Navbar Search -->
    <form class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0">
        <div class="input-group">
            <input type="text" class="form-control" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
            <div class="input-group-append">
                <button class="btn btn-primary" type="button">
                    <i class="fas fa-search"></i>
                </button>
            </div>
        </div>
    </form>

    <!-- Navbar -->
    <ul class="navbar-nav ml-auto ml-md-0">
        <li class="nav-item dropdown no-arrow mx-1">
            <a class="nav-link dropdown-toggle" href="#" id="alertsDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-bell fa-fw"></i>
                <span class="badge badge-danger">9+</span>
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="alertsDropdown">
                <a class="dropdown-item" href="#">Action</a>
                <a class="dropdown-item" href="#">Another action</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#">Something else here</a>
            </div>
        </li>
        <li class="nav-item dropdown no-arrow mx-1">
            <a class="nav-link dropdown-toggle" href="#" id="messagesDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-envelope fa-fw"></i>
                <span class="badge badge-danger">7</span>
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="messagesDropdown">
                <a class="dropdown-item" href="#">Action</a>
                <a class="dropdown-item" href="#">Another action</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#">Something else here</a>
            </div>
        </li>
        <li class="nav-item dropdown no-arrow">
            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-user-circle fa-fw"></i>
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
                <a class="dropdown-item" href="#">Settings</a>
                <a class="dropdown-item" href="#">Activity Log</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">Logout</a>
            </div>
        </li>
    </ul>
  </nav>

  <div id="wrapper">

    <!-- Sidebar -->
    <ul class="sidebar navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'soccer:index' %}">
          <i class="fas fa-fw fa-tachometer-alt"></i>
          <span>Dashboard</span>
        </a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="pagesDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fas fa-fw fa-folder"></i>
          <span>Pages</span>
        </a>
        <div class="dropdown-menu" aria-labelledby="pagesDropdown">
          <h6 class="dropdown-header">Login Screens:</h6>
          <a class="dropdown-item" href="{% url 'accounts:login' %}">Login</a>
          <a class="dropdown-item" href="">Register</a>
          <a class="dropdown-item" href="{% url 'accounts:password_reset' %}">Forgot Password</a>
          <div class="dropdown-divider"></div>
          <h6 class="dropdown-header">Other Pages:</h6>
          <a class="dropdown-item" href="404.html">404 Page</a>
          <a class="dropdown-item" href="blank.html">Blank Page</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'soccer:charts' %}">
          <i class="fas fa-fw fa-chart-area"></i>
          <span>Charts</span></a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="pagesDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fas fa-fw fa-folder"></i>
          <span>Demos</span>
        </a>
        <div class="dropdown-menu" aria-labelledby="pagesDropdown">
          <h6 class="dropdown-header">Simple Table - Record:</h6>
          <a class="dropdown-item" href="{% url 'demo:records' %}">Records (Class)</a>
          <a class="dropdown-item" href="{% url 'demo:records-json' %}">Records (Json, Class)</a>
          <a class="dropdown-item" href="{% url 'soccer:match' %}">Paginator (Client)</a>
          <a class="dropdown-item" href="">Paginator (Server)</a>
          <div class="dropdown-divider"></div>
          <h6 class="dropdown-header">Placeholder:</h6>
          <a class="dropdown-item" href="">Placeholder</a>
          <a class="dropdown-item" href="">Placeholder</a>
        </div>
      </li>
    </ul>

    <div id="content-wrapper">
      <div class="container-fluid">
        {% block content %}{% endblock %}
      </div>
      <!-- /.container-fluid -->

      <!-- Sticky Footer -->
      <footer class="sticky-footer">
        <div class="container my-auto">
            <div class="copyright text-center my-auto">
                <span>Copyright © Your Website 2019</span>
            </div>
        </div>
      </footer>

    </div>
    <!-- /.content-wrapper -->

  </div>
  <!-- /#wrapper -->

  <!-- Scroll to Top Button-->
  <a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
  </a>

  <!-- Logout Modal-->
  <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
          <button class="close" type="button" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
        </div>
        <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
        <div class="modal-footer">
          <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
          <a class="btn btn-primary" href="{% url 'accounts:logout' %}?next={% url 'accounts:login' %}">Logout</a>
        </div>
      </div>
    </div>
  </div>

  <!-- Bootstrap core JavaScript-->
  <script src="{% static 'jquery/3.4.1/jquery.min.js' %}"></script>
  <script src="{% static 'bootstrap/4.4.1/js/bootstrap.bundle.min.js' %}"></script>

  <!-- Core plugin JavaScript-->
  <script src="{% static 'jquery-easing/jquery.easing.min.js' %}"></script>

  <!-- Page level plugin JavaScript-->
  <script src="{% static 'chart.js/Chart.min.js' %}"></script>
  <script src="{% static 'datatables/jquery.dataTables.js' %}"></script>
  <script src="{% static 'datatables/dataTables.bootstrap4.js' %}"></script>

  <!-- Custom scripts for all pages-->
  <script src="{% static 'js/sb-admin.min.js' %}"></script>

  <!-- Demo scripts for this page-->
</body>
</html>

soccer/templates/index.html
{% extends "base_generic.html" %}

{% block title %}<title>Soccer</title>{% endblock %}

{% block content %}
  <!-- Breadcrumbs-->
  <ol class="breadcrumb">
    <li class="breadcrumb-item">
      <a href="#">Dashboard</a>
    </li>
    <li class="breadcrumb-item active">Overview</li>
  </ol>

  <!-- Icon Cards-->
  <div class="row">
    <div class="col-xl-3 col-sm-6 mb-3">
      <div class="card text-white bg-primary o-hidden h-100">
        <div class="card-body">
          <div class="card-body-icon">
            <i class="fas fa-fw fa-comments"></i>
          </div>
          <div class="mr-5">26 New Messages!</div>
        </div>
        <a class="card-footer text-white clearfix small z-1" href="#">
          <span class="float-left">View Details</span>
          <span class="float-right">
            <i class="fas fa-angle-right"></i>
          </span>
        </a>
      </div>
    </div>
    <div class="col-xl-3 col-sm-6 mb-3">
      <div class="card text-white bg-warning o-hidden h-100">
        <div class="card-body">
          <div class="card-body-icon">
            <i class="fas fa-fw fa-list"></i>
          </div>
          <div class="mr-5">11 New Tasks!</div>
        </div>
        <a class="card-footer text-white clearfix small z-1" href="#">
          <span class="float-left">View Details</span>
          <span class="float-right">
            <i class="fas fa-angle-right"></i>
          </span>
        </a>
      </div>
    </div>
    <div class="col-xl-3 col-sm-6 mb-3">
      <div class="card text-white bg-success o-hidden h-100">
        <div class="card-body">
          <div class="card-body-icon">
            <i class="fas fa-fw fa-shopping-cart"></i>
          </div>
          <div class="mr-5">123 New Orders!</div>
        </div>
        <a class="card-footer text-white clearfix small z-1" href="#">
          <span class="float-left">View Details</span>
          <span class="float-right">
            <i class="fas fa-angle-right"></i>
          </span>
        </a>
      </div>
    </div>
    <div class="col-xl-3 col-sm-6 mb-3">
      <div class="card text-white bg-danger o-hidden h-100">
        <div class="card-body">
          <div class="card-body-icon">
            <i class="fas fa-fw fa-life-ring"></i>
          </div>
          <div class="mr-5">13 New Tickets!</div>
        </div>
        <a class="card-footer text-white clearfix small z-1" href="#">
          <span class="float-left">View Details</span>
          <span class="float-right">
            <i class="fas fa-angle-right"></i>
          </span>
        </a>
      </div>
    </div>
  </div>

  <!-- Area Chart Example-->
  <div class="card mb-3">
    <div class="card-header">
      <i class="fas fa-chart-area"></i>
      Area Chart Example</div>
    <div class="card-body">
      <canvas id="myAreaChart" width="100%" height="30"></canvas>
    </div>
    <div class="card-footer small text-muted">Updated yesterday at 11:59 PM</div>
  </div>
{% endblock %}