catalog/urls.py
from django.urls import path
from . import views


app_name = 'catalog'

urlpatterns = [
    path('', views.index, name='index'),

    path('books/', views.BookListView.as_view(), name='books'),
    path('book/<int:pk>', views.BookDetailView.as_view(), name='book-detail'),

    path('book/create/', views.BookCreate.as_view(), name='book-create'),
    path('book/<int:pk>/update/', views.BookUpdate.as_view(), name='book-update'),
    path('book/<int:pk>/delete/', views.BookDelete.as_view(), name='book-delete'),

    path('mybooks/', views.LoanedBooksByUserListView.as_view(), name='my-borrowed'),
    path('borrowed/', views.LoanedBooksAllListView.as_view(), name='all-borrowed'),
    path('book/<uuid:pk>/renew/', views.renew_book_librarian, name='renew-book-librarian'),

    path('authors/', views.AuthorListView.as_view(), name='authors'),
    path('author/<int:pk>', views.AuthorDetailView.as_view(), name='author-detail'),

    path('author/create/', views.AuthorCreate.as_view(), name='author-create'),
    path('author/<int:pk>/update/', views.AuthorUpdate.as_view(), name='author-update'),
    path('author/<int:pk>/delete/', views.AuthorDelete.as_view(), name='author-delete'),
]

conf/urls.py
from django.urls import path, include
from django.views.generic.base import RedirectView
from django.views.i18n import JavaScriptCatalog
from django.conf.urls import url
# from django.contrib import admin
# from rest_framework import routers
# from common import views as common_views
from rest_framework_jwt.views import obtain_jwt_token


# router = routers.DefaultRouter()
# router.register(r'users', common_views.UserViewSet)

urlpatterns = [
    # use rest_framework router instead of URL conf
    # path('', include(router.urls)),

    # api authorization
    url(r'^api-token-auth/', obtain_jwt_token),
    # url('api-auth/', include('rest_framework.urls', namespace='rest_framework')),

    # shared
    path('favicon.ico', RedirectView.as_view(url=r'static/favicon.ico')),
    path('jsi18n/', JavaScriptCatalog.as_view(), name='javascript-catalog'),

    # app
    path('', include('common.urls')),
    # path('admin/', admin.site.urls),
]

catalog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
import uuid
from datetime import date


# Create your models here.
class Genre(models.Model):
    name = models.CharField('分类', max_length=200,
                            help_text='Enter a book genre (e.g. Science Fiction)')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '分类'
        verbose_name_plural = verbose_name


class Author(models.Model):
    first_name = models.CharField('名', max_length=100)
    last_name = models.CharField('姓', max_length=100)
    date_of_birth = models.DateField('出生日期', null=True, blank=True)
    date_of_death = models.DateField('死亡日期', null=True, blank=True)

    class Meta:
        ordering = ['last_name', 'first_name']
        verbose_name = '作者'
        verbose_name_plural = verbose_name

    def get_absolute_url(self):
        return reverse('catalog:author-detail', args=[str(self.id)])

    def __str__(self):
        return "%s, %s" % (self.last_name, self.first_name)


class Language(models.Model):
    name = models.CharField('语言', max_length=200,
                            help_text="Enter the book's natural language (e.g. English, French, Japanese etc.)")

    class Meta:
        verbose_name = '语言'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class Book(models.Model):
    title = models.CharField('书名', max_length=200)
    author = models.ForeignKey(Author, verbose_name='作者',
                               on_delete=models.SET_NULL, null=True)
    summary = models.TextField('摘要', max_length=1000,
                               help_text='Enter a brief description of the book')
    isbn = models.CharField('ISBN', max_length=13,
                            help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>')
    genre = models.ManyToManyField(Genre, verbose_name='分类',
                                   help_text='Select a genre for this book')
    language = models.ForeignKey(Language, verbose_name='语言', on_delete=models.SET_NULL, null=True)

    class Meta:
        verbose_name = '书籍'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('catalog:book-detail', args=[str(self.id)])

    def display_genre(self):
        return ', '.join(genre.name for genre in self.genre.all()[:3])

    display_genre.short_description = '所有分类'


class BookInstance(models.Model):
    id = models.UUIDField('ID', primary_key=True, default=uuid.uuid4,
                          help_text='Unique ID for this particular book across whole library')
    book = models.ForeignKey(Book, verbose_name='书籍', on_delete=models.SET_NULL, null=True)
    imprint = models.CharField('出版商名称', max_length=200)
    due_back = models.DateField('归还日期', null=True, blank=True)
    borrower = models.ForeignKey(User, verbose_name='出借人', on_delete=models.SET_NULL, null=True, blank=True)

    LOAN_STATUS = (
        ('m', 'Maintenance'),
        ('o', 'On loan'),
        ('a', 'Available'),
        ('r', 'Reserved'),
    )

    status = models.CharField('状态', max_length=1, choices=LOAN_STATUS, blank=True, default='m',
                              help_text='Book availability',)

    class Meta:
        ordering = ['due_back']
        verbose_name = '藏书'
        verbose_name_plural = verbose_name
        permissions = (("can_mark_returned", "Set book as returned"),)

    def __str__(self):
        return "%s (%s)" % (self.id, self.book.title)

    @property
    def is_overdue(self):
        if self.due_back and date.today() > self.due_back:
            return True
        return False

catalog/forms.py
import datetime
from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _
from .models import BookInstance


class RenewBookForm(forms.Form):
    renewal_date = forms.DateField(help_text="Enter a date between now and 4 weeks (default 3).")

    def clean_renewal_date(self):
        data = self.cleaned_data['renewal_date']

        # Check if a date is not in the past.
        if data < datetime.date.today():
            raise ValidationError(_('Invalid date - renewal in past'))

        # Check if a date is in the allowed range (+4 weeks from today).
        if data > datetime.date.today() + datetime.timedelta(weeks=4):
            raise ValidationError(_('Invalid date - renewal more than 4 weeks ahead'))

        # Remember to always return the cleaned data.
        return data


class RenewBookModelForm(forms.ModelForm):
    def clean_due_back(self):
        data = self.cleaned_data['due_back']

        # Check if a date is not in the past.
        if data < datetime.date.today():
            raise ValidationError(_('Invalid date - renewal in past'))

        # Check if a date is in the allowed range (+4 weeks from today).
        if data > datetime.date.today() + datetime.timedelta(weeks=4):
            raise ValidationError(_('Invalid date - renewal more than 4 weeks ahead'))

        # Remember to always return the cleaned data.
        return data

    class Meta:
        model = BookInstance
        fields = ['due_back']
        labels = {'due_back': _('New renewal date')}
        help_texts = {'due_back': _('Enter a date between now and 4 weeks (default 3).')}

catalog/views.py
import datetime
from django.shortcuts import render, get_object_or_404, reverse
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.auth.decorators import permission_required
from .models import Book, BookInstance, Author
from .forms import RenewBookForm, RenewBookModelForm


# Create your views here.
# function based
def index(request):
    num_books = Book.objects.all().count()
    num_instances = BookInstance.objects.all().count()

    # Available books (status = 'a')
    num_instances_available = BookInstance.objects.filter(status__exact='a').count()

    # The 'all()' is implied by default.
    num_authors = Author.objects.count()

    # Number of visits to this view, as counted in the session variable.
    num_visits = request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits + 1

    context = {
        'num_books': num_books,
        'num_instances': num_instances,
        'num_instances_available': num_instances_available,
        'num_authors': num_authors,
        'num_visits': num_visits,
    }

    return render(request, 'index.html', context=context)


# class-based
class BookListView(generic.ListView):
    model = Book
    # template_name = 'catalog/book_list.html'
    # context_object_name = 'book_list'
    paginate_by = 5

    # queryset = Book.objects.filter(title__icontains='Family')[:5]
    # def get_queryset(self):
        # return Book.objects.filter(title__icontains='Family')[:5]
        # return Book.objects.all()

    # def get_context_data(self, **kwargs):
    #     context = super(BookListView, self).get_context_data(**kwargs)
    #     context['some_data'] = 'This is just some data'
    #     return context


class BookDetailView(generic.DetailView):
    model = Book
    # template_name = 'catalog/book_detail.html'
    # context_object_name = 'book'


class AuthorListView(generic.ListView):
    model = Author
    # template_name = 'catalog/author_list.html'
    # context_object_name = 'author_list'
    paginate_by = 5


class AuthorDetailView(generic.DetailView):
    model = Author
    # template_name = 'catalog/author_detail.html'
    # context_object_name = 'author'


class LoanedBooksByUserListView(LoginRequiredMixin, generic.ListView):
    model = BookInstance
    template_name = 'catalog/bookinstance_list_borrowed_user.html'
    # context_object_name = 'bookinstance_list'
    paginate_by = 5

    def get_queryset(self):
        return BookInstance.objects.filter(borrower=self.request.user).filter(status__exact='o').order_by('due_back')


class LoanedBooksAllListView(PermissionRequiredMixin, generic.ListView):
    model = BookInstance
    template_name = 'catalog/bookinstance_list_borrowed_all.html'
    # context_object_name = 'bookinstance_list'
    paginate_by = 5
    permission_required = 'catalog.can_mark_returned'

    def get_queryset(self):
        return BookInstance.objects.filter(status__exact='o').order_by('due_back')


@permission_required('catalog.can_mark_returned')
def renew_book_librarian(request, pk):
    book_instance = get_object_or_404(BookInstance, pk=pk)

    if request.method == 'POST':
        # form = RenewBookForm(request.POST)
        form = RenewBookModelForm(request.POST)

        if form.is_valid():
            # book_instance.due_back = form.cleaned_data['renewal_date']
            book_instance.due_back = form.cleaned_data['due_back']
            book_instance.save()

            return HttpResponseRedirect(reverse('catalog:all-borrowed'))
    else:
        proposed_renewal_date = datetime.date.today() + datetime.timedelta(weeks=3)
        # form = RenewBookForm(initial={'renewal_date': proposed_renewal_date})
        form = RenewBookModelForm(initial={'due_back': proposed_renewal_date})

    context = {
        'form': form,
        'book_instance': book_instance,
    }

    return render(request, 'catalog/book_renew_librarian.html', context)


class AuthorCreate(LoginRequiredMixin, CreateView):
    model = Author
    fields = '__all__'
    initial = {'date_of_death': '2099/01/01'}
    # template_name = 'author_form.html'
    # success_url = reverse_lazy('catalog:authors')


class AuthorUpdate(LoginRequiredMixin, UpdateView):
    model = Author
    fields = ['first_name', 'last_name', 'date_of_birth', 'date_of_death']
    # success_url = reverse_lazy('catalog:author-detail', self.id)


class AuthorDelete(LoginRequiredMixin, DeleteView):
    model = Author
    # template_name = 'author_confirm_delete.html'
    success_url = reverse_lazy('catalog:authors')


class BookCreate(LoginRequiredMixin, CreateView):
    model = Book
    fields = '__all__'
    # template_name = 'book_form.html'
    # success_url = reverse_lazy('catalog:books')


class BookUpdate(LoginRequiredMixin, UpdateView):
    model = Book
    fields = ['title', 'author', 'summary', 'isbn', 'genre', 'language']
    # success_url = reverse_lazy('catalog:book-detail', self.id)


class BookDelete(LoginRequiredMixin, DeleteView):
    model = Book
    # template_name = 'book_confirm_delete.html'
    success_url = reverse_lazy('catalog:books')

catalog/templates/catalog/author_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Delete Author</h1>

<p>Are you sure you want to delete the author: {{ author }}?</p>

<form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes, delete.">
</form>

{% endblock %}

catalog/templates/catalog/author_detail.html
{% extends "base_generic.html" %}

{% block content %}
<h1>Author: {{ author }}</h1>

<p>{{ author.date_of_birth|default:'' }} - {{ author.date_of_death|default:'' }}</p>

<div style="margin-left:20px;margin-top:20px">
    <h4>Books</h4>

    {% for book in author.book_set.all %}
    <hr>
    <p><strong><a href="{% url 'catalog:book-detail' book.pk %}">{{ book.title }}</a> ({{
        book.bookinstance_set.all.count }})</strong></p>
    <p>{{ book.summary }}</p>
    {% endfor %}
</div>
{% endblock %}

catalog/templates/catalog/author_form.html
{% extends "base_generic.html" %}

{% block content %}
<form action="" method="post">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
</form>
{% endblock %}

catalog/templates/catalog/author_list.html
{% extends "base_generic.html" %}

{% block content %}
<h1>Author List</h1>
{% if user.is_staff %}
<a href="{% url 'catalog:author-create' %}">[NEW]</a>
{% endif %}
{% if author_list %}
<ul>
    {% for author in author_list %}
    <li>
        <a href="{% url 'catalog:author-detail' author.pk %}">{{ author }} ({{ author.date_of_birth|default:'' }} - {{
            author.date_of_death|default:'' }})</a>{% if user.is_staff %} - <a
            href="{% url 'catalog:author-update' author.pk %}">[EDIT]</a> <a
            href="{% url 'catalog:author-delete' author.pk %}">[DEL]</a> {% endif %}
    </li>
    {% endfor %}
</ul>
{% else %}
<p>There are no authors in the library.</p>
{% endif %}
{% endblock %}

catalog/templates/catalog/book_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Delete Book</h1>

<p>Are you sure you want to delete the book: {{ book }}?</p>

<form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes, delete.">
</form>

{% endblock %}

catalog/templates/catalog/book_detail.html
{% extends "base_generic.html" %}

{% block content %}
<h1>Title: {{ book.title }}</h1>

<p><strong>Author:</strong> <a href="{% url 'catalog:author-detail' book.author.pk %}">{{ book.author }}</a>
</p> <!-- author detail link not yet defined -->
<p><strong>Summary:</strong> {{ book.summary }}</p>
<p><strong>ISBN:</strong> {{ book.isbn }}</p>
<p><strong>Language:</strong> {{ book.language }}</p>
<p><strong>Genre:</strong> {{ book.genre.all|join:", " }}</p>

<div style="margin-left:20px;margin-top:20px">
    <h4>Copies</h4>

    {% for copy in book.bookinstance_set.all %}
    <hr>
    <p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'm' %}text-danger{% else %}text-warning{% endif %}">
        {{ copy.get_status_display }}
    </p>
    {% if copy.status != 'a' %}
    <p><strong>Due to be returned:</strong> {{ copy.due_back }}</p>
    {% endif %}
    <p><strong>Imprint:</strong> {{ copy.imprint }}</p>
    <p class="text-muted"><strong>Id:</strong> {{ copy.id }}</p>
    {% endfor %}
</div>
{% endblock %}

catalog/templates/catalog/book_form.html
{% extends "base_generic.html" %}

{% block content %}
<form action="" method="post">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
</form>
{% endblock %}

catalog/templates/catalog/book_list.html
{% extends "base_generic.html" %}

{% block content %}
<h1>Book List</h1>
{% if user.is_staff %}
<a href="{% url 'catalog:book-create' %}">[NEW]</a>
{% endif %}
{% if book_list %}
<ul>
    {% for book in book_list %}
    <li>
        <a href="{% url 'catalog:book-detail' book.pk %}">{{ book.title }}</a> ({{book.author}}) {% if user.is_staff
        %}<a href="{% url 'catalog:book-update' book.id %}">[EDIT]</a><a href="{% url 'catalog:book-delete' book.id %}">[DEL]</a>
        {% endif %}
    </li>
    {% endfor %}
</ul>
{% else %}
<p>There are no books in the library.</p>
{% endif %}
{% endblock %}

catalog/templates/catalog/book_renew_librarian.html
{% extends "base_generic.html" %}

{% block content %}
<h1>Renew: {{ book_instance.book.title }}</h1>
<p>Borrower: {{ book_instance.borrower }}</p>
<p{% if book_instance.is_overdue %} class="text-danger"{% endif %}>Due date: {{ book_instance.due_back }}</p>

<form action="" method="post">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
</form>
{% endblock %}

catalog/templates/catalog/bookinstance_list_borrowed_all.html
{% extends "base_generic.html" %}

{% block content %}
<h1>All Borrowed Books</h1>

{% if bookinstance_list %}
<ul>

    {% for bookinst in bookinstance_list %}
    <li class="{% if bookinst.is_overdue %}text-danger{% endif %}">
        <a href="{% url 'catalog:book-detail' bookinst.book.pk %}">{{ bookinst.book.title }}</a> ({{ bookinst.due_back
        }}) {% if user.is_staff %}- {{ bookinst.borrower }}{% endif %} {% if perms.catalog.can_mark_returned %}- <a
            href="{% url 'catalog:renew-book-librarian' bookinst.id %}">[RENEW]</a> {% endif %}
    </li>
    {% endfor %}
</ul>

{% else %}
<p>There are no books borrowed.</p>
{% endif %}
{% endblock %}

catalog/templates/catalog/bookinstance_list_borrowed_user.html
{% extends "base_generic.html" %}

{% block content %}
<h1>Borrowed books</h1>

{% if bookinstance_list %}
<ul>

    {% for bookinst in bookinstance_list %}
    <li class="{% if bookinst.is_overdue %}text-danger{% endif %}">
        <a href="{% url 'catalog:book-detail' bookinst.book.pk %}">{{ bookinst.book.title }}</a> ({{ bookinst.due_back
        }})
    </li>
    {% endfor %}
</ul>

{% else %}
<p>There are no books borrowed.</p>
{% endif %}
{% endblock %}